
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadImage(path: string) : Promise<LoadImageResult> {
    return await TAURI_INVOKE("load_image", { path });
},
async applyAdjustments(jsAdjustments: JsonValue, isInteractive: boolean) : Promise<null> {
    return await TAURI_INVOKE("apply_adjustments", { jsAdjustments, isInteractive });
},
async exportImage(originalPath: string, outputPath: string, jsAdjustments: JsonValue, exportSettings: ExportSettings) : Promise<null> {
    return await TAURI_INVOKE("export_image", { originalPath, outputPath, jsAdjustments, exportSettings });
},
async batchExportImages(outputFolder: string, paths: string[], exportSettings: ExportSettings, outputFormat: string) : Promise<null> {
    return await TAURI_INVOKE("batch_export_images", { outputFolder, paths, exportSettings, outputFormat });
},
async cancelExport() : Promise<null> {
    return await TAURI_INVOKE("cancel_export");
},
async estimateExportSize(jsAdjustments: JsonValue, exportSettings: ExportSettings, outputFormat: string) : Promise<number> {
    return await TAURI_INVOKE("estimate_export_size", { jsAdjustments, exportSettings, outputFormat });
},
async estimateBatchExportSize(paths: string[], exportSettings: ExportSettings, outputFormat: string) : Promise<number> {
    return await TAURI_INVOKE("estimate_batch_export_size", { paths, exportSettings, outputFormat });
},
async generateFullscreenPreview(jsAdjustments: JsonValue) : Promise<null> {
    return await TAURI_INVOKE("generate_fullscreen_preview", { jsAdjustments });
},
async generatePreviewForPath(path: string, jsAdjustments: JsonValue) : Promise<number[]> {
    return await TAURI_INVOKE("generate_preview_for_path", { path, jsAdjustments });
},
async generateOriginalTransformedPreview(jsAdjustments: JsonValue) : Promise<number[]> {
    return await TAURI_INVOKE("generate_original_transformed_preview", { jsAdjustments });
},
async generatePresetPreview(jsAdjustments: JsonValue) : Promise<number[]> {
    return await TAURI_INVOKE("generate_preset_preview", { jsAdjustments });
},
async generateUncroppedPreview(jsAdjustments: JsonValue) : Promise<null> {
    return await TAURI_INVOKE("generate_uncropped_preview", { jsAdjustments });
},
async previewGeometryTransform(params: GeometryParams, jsAdjustments: JsonValue, showLines: boolean) : Promise<string> {
    return await TAURI_INVOKE("preview_geometry_transform", { params, jsAdjustments, showLines });
},
async generateMaskOverlay(maskDef: MaskDefinition, width: number, height: number, scale: number, cropOffset: [number, number]) : Promise<string> {
    return await TAURI_INVOKE("generate_mask_overlay", { maskDef, width, height, scale, cropOffset });
},
async generateAiSubjectMask(jsAdjustments: JsonValue, path: string, startPoint: [number, number], endPoint: [number, number], rotation: number, flipHorizontal: boolean, flipVertical: boolean, orientationSteps: number) : Promise<AiSubjectMaskParameters> {
    return await TAURI_INVOKE("generate_ai_subject_mask", { jsAdjustments, path, startPoint, endPoint, rotation, flipHorizontal, flipVertical, orientationSteps });
},
async generateAiForegroundMask(jsAdjustments: JsonValue, rotation: number, flipHorizontal: boolean, flipVertical: boolean, orientationSteps: number) : Promise<AiForegroundMaskParameters> {
    return await TAURI_INVOKE("generate_ai_foreground_mask", { jsAdjustments, rotation, flipHorizontal, flipVertical, orientationSteps });
},
async generateAiSkyMask(jsAdjustments: JsonValue, rotation: number, flipHorizontal: boolean, flipVertical: boolean, orientationSteps: number) : Promise<AiSkyMaskParameters> {
    return await TAURI_INVOKE("generate_ai_sky_mask", { jsAdjustments, rotation, flipHorizontal, flipVertical, orientationSteps });
},
async updateWindowEffect(theme: string) : Promise<void> {
    await TAURI_INVOKE("update_window_effect", { theme });
},
async checkAiConnectorStatus() : Promise<void> {
    await TAURI_INVOKE("check_ai_connector_status");
},
async testAiConnectorConnection(address: string) : Promise<null> {
    return await TAURI_INVOKE("test_ai_connector_connection", { address });
},
async invokeGenerativeReplaceWithMaskDef(path: string, patchDefinition: AiPatchDefinition, currentAdjustments: JsonValue, useFastInpaint: boolean, token: string | null) : Promise<string> {
    return await TAURI_INVOKE("invoke_generative_replace_with_mask_def", { path, patchDefinition, currentAdjustments, useFastInpaint, token });
},
async getSupportedFileTypes() : Promise<JsonValue> {
    return await TAURI_INVOKE("get_supported_file_types");
},
async getLogFilePath() : Promise<string> {
    return await TAURI_INVOKE("get_log_file_path");
},
async frontendLog(level: string, message: string) : Promise<null> {
    return await TAURI_INVOKE("frontend_log", { level, message });
},
async saveCollage(base64Data: string, firstPathStr: string) : Promise<string> {
    return await TAURI_INVOKE("save_collage", { base64Data, firstPathStr });
},
async stitchPanorama(paths: string[]) : Promise<null> {
    return await TAURI_INVOKE("stitch_panorama", { paths });
},
async savePanorama(firstPathStr: string) : Promise<string> {
    return await TAURI_INVOKE("save_panorama", { firstPathStr });
},
async mergeHdr(paths: string[]) : Promise<null> {
    return await TAURI_INVOKE("merge_hdr", { paths });
},
async saveHdr(firstPathStr: string) : Promise<string> {
    return await TAURI_INVOKE("save_hdr", { firstPathStr });
},
async applyDenoising(path: string, intensity: number) : Promise<null> {
    return await TAURI_INVOKE("apply_denoising", { path, intensity });
},
async saveDenoisedImage(originalPathStr: string) : Promise<string> {
    return await TAURI_INVOKE("save_denoised_image", { originalPathStr });
},
async loadAndParseLut(path: string) : Promise<LutParseResult> {
    return await TAURI_INVOKE("load_and_parse_lut", { path });
},
async fetchCommunityPresets() : Promise<CommunityPreset[]> {
    return await TAURI_INVOKE("fetch_community_presets");
},
async generateAllCommunityPreviews(imagePaths: string[], presets: CommunityPreset[]) : Promise<Partial<{ [key in string]: number[] }>> {
    return await TAURI_INVOKE("generate_all_community_previews", { imagePaths, presets });
},
async saveTempFile(bytes: number[]) : Promise<string> {
    return await TAURI_INVOKE("save_temp_file", { bytes });
},
async getImageDimensions(path: string) : Promise<ImageDimensions> {
    return await TAURI_INVOKE("get_image_dimensions", { path });
},
async frontendReady() : Promise<null> {
    return await TAURI_INVOKE("frontend_ready");
},
async cancelThumbnailGeneration() : Promise<null> {
    return await TAURI_INVOKE("cancel_thumbnail_generation");
},
async generateHistogram() : Promise<HistogramData> {
    return await TAURI_INVOKE("generate_histogram");
},
async generateWaveform() : Promise<WaveformData> {
    return await TAURI_INVOKE("generate_waveform");
},
async calculateAutoAdjustments() : Promise<JsonValue> {
    return await TAURI_INVOKE("calculate_auto_adjustments");
},
async readExifForPaths(paths: string[]) : Promise<Partial<{ [key in string]: Partial<{ [key in string]: string }> }>> {
    return await TAURI_INVOKE("read_exif_for_paths", { paths });
},
async listImagesInDir(path: string) : Promise<ImageFile[]> {
    return await TAURI_INVOKE("list_images_in_dir", { path });
},
async listImagesRecursive(path: string) : Promise<ImageFile[]> {
    return await TAURI_INVOKE("list_images_recursive", { path });
},
async getFolderTree(path: string) : Promise<FolderNode> {
    return await TAURI_INVOKE("get_folder_tree", { path });
},
async getPinnedFolderTrees(paths: string[]) : Promise<FolderNode[]> {
    return await TAURI_INVOKE("get_pinned_folder_trees", { paths });
},
async generateThumbnails(paths: string[]) : Promise<Partial<{ [key in string]: string }>> {
    return await TAURI_INVOKE("generate_thumbnails", { paths });
},
async generateThumbnailsProgressive(paths: string[]) : Promise<null> {
    return await TAURI_INVOKE("generate_thumbnails_progressive", { paths });
},
async createFolder(path: string) : Promise<null> {
    return await TAURI_INVOKE("create_folder", { path });
},
async deleteFolder(path: string) : Promise<null> {
    return await TAURI_INVOKE("delete_folder", { path });
},
async copyFiles(sourcePaths: string[], destinationFolder: string) : Promise<null> {
    return await TAURI_INVOKE("copy_files", { sourcePaths, destinationFolder });
},
async moveFiles(sourcePaths: string[], destinationFolder: string) : Promise<null> {
    return await TAURI_INVOKE("move_files", { sourcePaths, destinationFolder });
},
async renameFolder(path: string, newName: string) : Promise<null> {
    return await TAURI_INVOKE("rename_folder", { path, newName });
},
async renameFiles(paths: string[], nameTemplate: string) : Promise<string[]> {
    return await TAURI_INVOKE("rename_files", { paths, nameTemplate });
},
async duplicateFile(path: string) : Promise<null> {
    return await TAURI_INVOKE("duplicate_file", { path });
},
async showInFinder(path: string) : Promise<null> {
    return await TAURI_INVOKE("show_in_finder", { path });
},
async deleteFilesFromDisk(paths: string[]) : Promise<null> {
    return await TAURI_INVOKE("delete_files_from_disk", { paths });
},
async deleteFilesWithAssociated(paths: string[]) : Promise<null> {
    return await TAURI_INVOKE("delete_files_with_associated", { paths });
},
async saveMetadataAndUpdateThumbnail(path: string, adjustments: JsonValue) : Promise<null> {
    return await TAURI_INVOKE("save_metadata_and_update_thumbnail", { path, adjustments });
},
async applyAdjustmentsToPaths(paths: string[], adjustments: JsonValue) : Promise<null> {
    return await TAURI_INVOKE("apply_adjustments_to_paths", { paths, adjustments });
},
async loadMetadata(path: string) : Promise<ImageMetadata> {
    return await TAURI_INVOKE("load_metadata", { path });
},
async loadPresets() : Promise<PresetItem[]> {
    return await TAURI_INVOKE("load_presets");
},
async savePresets(presets: PresetItem[]) : Promise<null> {
    return await TAURI_INVOKE("save_presets", { presets });
},
async loadSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("load_settings");
},
async saveSettings(settings: AppSettings) : Promise<null> {
    return await TAURI_INVOKE("save_settings", { settings });
},
async resetAdjustmentsForPaths(paths: string[]) : Promise<null> {
    return await TAURI_INVOKE("reset_adjustments_for_paths", { paths });
},
async applyAutoAdjustmentsToPaths(paths: string[]) : Promise<null> {
    return await TAURI_INVOKE("apply_auto_adjustments_to_paths", { paths });
},
async handleImportPresetsFromFile(filePath: string) : Promise<PresetItem[]> {
    return await TAURI_INVOKE("handle_import_presets_from_file", { filePath });
},
async handleImportLegacyPresetsFromFile(filePath: string) : Promise<PresetItem[]> {
    return await TAURI_INVOKE("handle_import_legacy_presets_from_file", { filePath });
},
async handleExportPresetsToFile(presetsToExport: PresetItem[], filePath: string) : Promise<null> {
    return await TAURI_INVOKE("handle_export_presets_to_file", { presetsToExport, filePath });
},
async saveCommunityPreset(name: string, adjustments: JsonValue) : Promise<null> {
    return await TAURI_INVOKE("save_community_preset", { name, adjustments });
},
async clearAllSidecars(rootPath: string) : Promise<number> {
    return await TAURI_INVOKE("clear_all_sidecars", { rootPath });
},
async clearThumbnailCache() : Promise<null> {
    return await TAURI_INVOKE("clear_thumbnail_cache");
},
async setColorLabelForPaths(paths: string[], color: string | null) : Promise<null> {
    return await TAURI_INVOKE("set_color_label_for_paths", { paths, color });
},
async importFiles(sourcePaths: string[], destinationFolder: string, settings: ImportSettings) : Promise<null> {
    return await TAURI_INVOKE("import_files", { sourcePaths, destinationFolder, settings });
},
async createVirtualCopy(sourceVirtualPath: string) : Promise<string> {
    return await TAURI_INVOKE("create_virtual_copy", { sourceVirtualPath });
},
async startBackgroundIndexing(folderPath: string) : Promise<null> {
    return await TAURI_INVOKE("start_background_indexing", { folderPath });
},
async clearAiTags(rootPath: string) : Promise<number> {
    return await TAURI_INVOKE("clear_ai_tags", { rootPath });
},
async clearAllTags(rootPath: string) : Promise<number> {
    return await TAURI_INVOKE("clear_all_tags", { rootPath });
},
async addTagForPaths(paths: string[], tag: string) : Promise<null> {
    return await TAURI_INVOKE("add_tag_for_paths", { paths, tag });
},
async removeTagForPaths(paths: string[], tag: string) : Promise<null> {
    return await TAURI_INVOKE("remove_tag_for_paths", { paths, tag });
},
async cullImages(paths: string[], settings: CullingSettings) : Promise<CullingSuggestions> {
    return await TAURI_INVOKE("cull_images", { paths, settings });
},
async getLensfunMakers() : Promise<string[]> {
    return await TAURI_INVOKE("get_lensfun_makers");
},
async getLensfunLensesForMaker(maker: string) : Promise<string[]> {
    return await TAURI_INVOKE("get_lensfun_lenses_for_maker", { maker });
},
async autodetectLens(maker: string, model: string) : Promise<[string, string] | null> {
    return await TAURI_INVOKE("autodetect_lens", { maker, model });
},
async getLensDistortionParams(maker: string, model: string, focalLength: number, aperture: number | null, distance: number | null) : Promise<LensDistortionParams | null> {
    return await TAURI_INVOKE("get_lens_distortion_params", { maker, model, focalLength, aperture, distance });
},
async previewNegativeConversion(path: string, params: NegativeConversionParams) : Promise<string> {
    return await TAURI_INVOKE("preview_negative_conversion", { path, params });
},
async convertNegativeFull(path: string, params: NegativeConversionParams) : Promise<null> {
    return await TAURI_INVOKE("convert_negative_full", { path, params });
},
async saveConvertedNegative(originalPathStr: string) : Promise<string> {
    return await TAURI_INVOKE("save_converted_negative", { originalPathStr });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
aiConnectorStatusUpdate: AiConnectorStatusUpdate
}>({
aiConnectorStatusUpdate: "ai-connector-status-update"
})

/** user-defined constants **/



/** user-defined types **/

export type AiConnectorStatusUpdate = { connected: boolean }
export type AiForegroundMaskParameters = { maskDataBase64?: string | null; rotation?: number | null; flipHorizontal?: boolean | null; flipVertical?: boolean | null; orientationSteps?: number | null }
export type AiPatchDefinition = { id: string; name: string; visible: boolean; invert: boolean; prompt: string; patchData?: PatchData | null; opacity?: number; subMasks: SubMask[] }
export type AiSkyMaskParameters = { maskDataBase64?: string | null; rotation?: number | null; flipHorizontal?: boolean | null; flipVertical?: boolean | null; orientationSteps?: number | null }
export type AiSubjectMaskParameters = { startX: number; startY: number; endX: number; endY: number; maskDataBase64?: string | null; rotation?: number | null; flipHorizontal?: boolean | null; flipVertical?: boolean | null; orientationSteps?: number | null }
export type AppSettings = { lastRootPath: string | null; pinnedFolders?: string[]; editorPreviewResolution: number | null; enableZoomHifi?: boolean | null; enableLivePreviews?: boolean | null; enableHighQualityLivePreviews?: boolean | null; sortCriteria: SortCriteria | null; filterCriteria: FilterCriteria | null; theme: string | null; transparent: boolean | null; decorations: boolean | null; aiConnectorAddress: string | null; lastFolderState: LastFolderState | null; adaptiveEditorTheme: boolean | null; uiVisibility: JsonValue | null; enableAiTagging: boolean | null; taggingThreadCount: number | null; taggingShortcuts?: string[] | null; customAiTags?: string[] | null; aiTagCount?: number | null; thumbnailSize: string | null; thumbnailAspectRatio: string | null; aiProvider: string | null; adjustmentVisibility?: Partial<{ [key in string]: boolean }>; enableExifReading: boolean | null; activeTreeSection?: string | null; copyPasteSettings?: CopyPasteSettings; rawHighlightCompression?: number | null; processingBackend?: string | null; linuxGpuOptimization?: boolean | null; libraryViewMode?: string | null; exportPresets?: ExportPreset[]; myLenses?: MyLens[] | null; enableFolderImageCounts?: boolean | null; linearRawMode?: string; enableXmpSync?: boolean | null; createXmpIfMissing?: boolean | null }
export type CommunityPreset = { name: string; creator: string; adjustments: JsonValue }
export type CopyPasteSettings = { mode: PasteMode; includedAdjustments?: string[]; knownAdjustments?: string[] }
export type CullGroup = { representative: ImageAnalysisResult; duplicates: ImageAnalysisResult[] }
export type CullingSettings = { similarityThreshold: number; blurThreshold: number; groupSimilar: boolean; filterBlurry: boolean }
export type CullingSuggestions = { similarGroups: CullGroup[]; blurryImages: ImageAnalysisResult[]; failedPaths: string[] }
export type ExportPreset = { id: string; name: string; fileFormat: string; jpegQuality: number; enableResize: boolean; resizeMode: string; resizeValue: number; dontEnlarge: boolean; keepMetadata: boolean; stripGps: boolean; filenameTemplate: string; enableWatermark: boolean; watermarkPath: string | null; watermarkAnchor: string | null; watermarkScale: number; watermarkSpacing: number; watermarkOpacity: number; exportMasks?: boolean | null }
export type ExportSettings = { jpegQuality: number; resize: ResizeOptions | null; keepMetadata: boolean; stripGps: boolean; filenameTemplate: string | null; watermark: WatermarkSettings | null; exportMasks?: boolean }
export type FilterCriteria = { rating: number; rawStatus: string; colors?: string[] }
export type FolderNode = { name: string; path: string; children: FolderNode[]; isDir: boolean; imageCount: number }
export type GeometryParams = { distortion: number; vertical: number; horizontal: number; rotate: number; aspect: number; scale: number; x_offset: number; y_offset: number; lens_distortion_amount: number; lens_vignette_amount: number; lens_tca_amount: number; lens_distortion_enabled: boolean; lens_tca_enabled: boolean; lens_vignette_enabled: boolean; lens_auto_crop: boolean; lens_dist_k1: number; lens_dist_k2: number; lens_dist_k3: number; lens_model: number; tca_vr: number; tca_vb: number; vig_k1: number; vig_k2: number; vig_k3: number }
export type HistogramData = { red: number[]; green: number[]; blue: number[]; luma: number[] }
export type ImageAnalysisResult = { path: string; qualityScore: number; sharpnessMetric: number; centerFocusMetric: number; exposureMetric: number; width: number; height: number }
export type ImageDimensions = { width: number; height: number }
export type ImageFile = { path: string; modified: number; is_edited: boolean; tags: string[] | null; exif: Partial<{ [key in string]: string }> | null; is_virtual_copy: boolean }
export type ImageMetadata = { version: number; rating: number; adjustments: JsonValue; tags?: string[] | null }
export type ImportSettings = { filenameTemplate: string; organizeByDate: boolean; dateFolderFormat: string; deleteAfterImport: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LastFolderState = { currentFolderPath: string; expandedFolders: string[] }
export type LensDistortionParams = { k1: number; k2: number; k3: number; model: number; tca_vr: number; tca_vb: number; vig_k1: number; vig_k2: number; vig_k3: number }
export type LoadImageResult = { width: number; height: number; metadata: ImageMetadata; exif: Partial<{ [key in string]: string }>; is_raw: boolean }
export type LutParseResult = { size: number }
export type MaskDefinition = { id: string; name: string; visible: boolean; invert: boolean; opacity?: number; adjustments: JsonValue; subMasks: SubMask[] }
export type MyLens = { maker: string; model: string }
export type NegativeConversionParams = { red_weight: number; green_weight: number; blue_weight: number; exposure: number; contrast: number }
export type PasteMode = "merge" | "replace"
export type PatchData = { color: string; mask: string }
export type Preset = { id: string; name: string; adjustments: JsonValue }
export type PresetFolder = { id: string; name: string; children: Preset[] }
export type PresetItem = { preset: Preset } | { folder: PresetFolder }
export type ResizeMode = "longEdge" | "shortEdge" | "width" | "height"
export type ResizeOptions = { mode: ResizeMode; value: number; dontEnlarge: boolean }
export type SortCriteria = { key: string; order: string }
export type SubMask = { id: string; type: string; visible: boolean; invert?: boolean; opacity?: number; mode: SubMaskMode; parameters: JsonValue }
export type SubMaskMode = "additive" | "subtractive"
export type WatermarkAnchor = "topLeft" | "topCenter" | "topRight" | "centerLeft" | "center" | "centerRight" | "bottomLeft" | "bottomCenter" | "bottomRight"
export type WatermarkSettings = { path: string; anchor: WatermarkAnchor; scale: number; spacing: number; opacity: number }
export type WaveformData = { red: number[]; green: number[]; blue: number[]; luma: number[]; width: number; height: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
