// Stable action IDs are shared by dispatch, settings and shortcut hints.
// prettier-ignore
const entries = [
  ["open_image", "settings.keybinds.actions.open_image", ["Enter"], "library"],
  ["copy_files", "settings.keybinds.actions.copy_files", ["ctrl", "shift", "KeyC"], "library"],
  ["paste_files", "settings.keybinds.actions.paste_files", ["ctrl", "shift", "KeyV"], "library"],
  ["copy_image_path", "settings.keybinds.actions.copy_image_path", ["ctrl", "KeyL"], "library"],
  ["select_all", "settings.keybinds.actions.select_all", ["ctrl", "KeyA"], "library"],
  ["delete_selected", "settings.keybinds.actions.delete_selected", ["Delete"], "library"],
  ["preview_prev", "settings.keybinds.actions.preview_prev", ["ArrowLeft"], "library"],
  ["preview_next", "settings.keybinds.actions.preview_next", ["ArrowRight"], "library"],
  ["zoom_in_step", "settings.keybinds.actions.zoom_in_step", ["ArrowUp"], "view"],
  ["zoom_out_step", "settings.keybinds.actions.zoom_out_step", ["ArrowDown"], "view"],
  ["cycle_zoom", "settings.keybinds.actions.cycle_zoom", ["Space"], "view"],
  ["zoom_in", "settings.keybinds.actions.zoom_in", ["ctrl", "Equal"], "view"],
  ["zoom_out", "settings.keybinds.actions.zoom_out", ["ctrl", "Minus"], "view"],
  ["zoom_fit", "settings.keybinds.actions.zoom_fit", ["ctrl", "Digit0"], "view"],
  ["zoom_100", "settings.keybinds.actions.zoom_100", ["ctrl", "Digit1"], "view"],
  ["toggle_fullscreen", "settings.keybinds.actions.toggle_fullscreen", ["KeyF"], "view"],
  ["show_original", "settings.keybinds.actions.show_original", ["KeyB"], "view"],
  ["rate_0", "settings.keybinds.actions.rate_0", ["Digit0"], "rating"],
  ["rate_1", "settings.keybinds.actions.rate_1", ["Digit1"], "rating"],
  ["rate_2", "settings.keybinds.actions.rate_2", ["Digit2"], "rating"],
  ["rate_3", "settings.keybinds.actions.rate_3", ["Digit3"], "rating"],
  ["rate_4", "settings.keybinds.actions.rate_4", ["Digit4"], "rating"],
  ["rate_5", "settings.keybinds.actions.rate_5", ["Digit5"], "rating"],
  ["color_label_none", "settings.keybinds.actions.color_label_none", ["shift", "Digit0"], "rating"],
  ["color_label_red", "settings.keybinds.actions.color_label_red", ["shift", "Digit1"], "rating"],
  ["color_label_yellow", "settings.keybinds.actions.color_label_yellow", ["shift", "Digit2"], "rating"],
  ["color_label_green", "settings.keybinds.actions.color_label_green", ["shift", "Digit3"], "rating"],
  ["color_label_blue", "settings.keybinds.actions.color_label_blue", ["shift", "Digit4"], "rating"],
  ["color_label_purple", "settings.keybinds.actions.color_label_purple", ["shift", "Digit5"], "rating"],
  ["toggle_adjustments", "settings.keybinds.actions.toggle_adjustments", ["KeyD"], "panels"],
  ["toggle_crop_panel", "settings.keybinds.actions.toggle_crop_panel", ["KeyR"], "panels"],
  ["toggle_masks", "settings.keybinds.actions.toggle_masks", ["KeyM"], "panels"],
  ["toggle_ai", "settings.keybinds.actions.toggle_ai", ["KeyK"], "panels"],
  ["toggle_presets", "settings.keybinds.actions.toggle_presets", ["KeyP"], "panels"],
  ["toggle_metadata", "settings.keybinds.actions.toggle_metadata", ["KeyI"], "panels"],
  ["toggle_folder_tree", "settings.keybinds.actions.toggle_folder_tree", ["KeyL"], "panels"],
  ["toggle_analytics", "settings.keybinds.actions.toggle_analytics", ["KeyA"], "panels"],
  ["toggle_export", "settings.keybinds.actions.toggle_export", ["KeyE"], "panels"],
  ["toggle_left_panel", "settings.keybinds.actions.toggle_left_panel", ["ctrl", "shift", "KeyB"], "panels"],
  ["toggle_right_panel", "settings.keybinds.actions.toggle_right_panel", ["ctrl", "KeyB"], "panels"],
  ["toggle_bottom_panel", "settings.keybinds.actions.toggle_bottom_panel", ["ctrl", "KeyJ"], "panels"],
  ["toggle_library_exif", "settings.keybinds.actions.toggle_library_exif", ["KeyT"], "library"],
  ["open_settings", "settings.keybinds.actions.open_settings", ["ctrl", "Comma"], "library"],
  ["focus_search", "settings.keybinds.actions.focus_search", ["ctrl", "KeyF"], "library"],
  ["undo", "settings.keybinds.actions.undo", ["ctrl", "KeyZ"], "editing"],
  ["redo", "settings.keybinds.actions.redo", ["ctrl", "KeyY"], "editing"],
  ["copy_adjustments", "settings.keybinds.actions.copy_adjustments", ["ctrl", "KeyC"], "editing"],
  ["paste_adjustments", "settings.keybinds.actions.paste_adjustments", ["ctrl", "KeyV"], "editing"],
  ["sync_adjustments", "modals.copyPaste.autoSyncTitle", ["ctrl", "shift", "KeyS"], "editing"],
  ["rotate_left", "settings.keybinds.actions.rotate_left", ["BracketLeft"], "editing"],
  ["rotate_right", "settings.keybinds.actions.rotate_right", ["BracketRight"], "editing"],
  ["toggle_crop", "settings.keybinds.actions.toggle_crop", ["KeyS"], "editing"],
  ["brush_size_up", "settings.keybinds.actions.brush_size_up", ["ctrl", "ArrowUp"], "editing"],
  ["brush_size_down", "settings.keybinds.actions.brush_size_down", ["ctrl", "ArrowDown"], "editing"],
  ["gallery", "shortcuts.actions.gallery", ["KeyG"], "library"],
  ["develop", "shortcuts.actions.develop", [], "editing"],
  ["crop_accept", "shortcuts.actions.crop_accept", ["Enter"], "crop"],
  ["crop_cancel", "shortcuts.actions.crop_cancel", ["Escape"], "crop"],
  ["crop_lock", "shortcuts.actions.crop_lock", [], "crop"],
  ["crop_orientation", "shortcuts.actions.crop_orientation", [], "crop"],
  ["crop_overlay", "shortcuts.actions.crop_overlay", ["KeyO"], "crop"],
  ["crop_overlay_rotate", "shortcuts.actions.crop_overlay_rotate", ["shift", "KeyO"], "crop"],
  ["crop_reset", "shortcuts.actions.crop_reset", [], "crop"],
  ["crop_flip_h", "shortcuts.actions.crop_flip_h", [], "crop"],
  ["crop_flip_v", "shortcuts.actions.crop_flip_v", [], "crop"],
  ["crop_drag_mode", "shortcuts.actions.crop_drag_mode", [], "crop"],
  ["crop_left", "shortcuts.actions.crop_left", ["ArrowLeft"], "crop"],
  ["crop_right", "shortcuts.actions.crop_right", ["ArrowRight"], "crop"],
  ["crop_up", "shortcuts.actions.crop_up", ["ArrowUp"], "crop"],
  ["crop_down", "shortcuts.actions.crop_down", ["ArrowDown"], "crop"],
  ["library_left", "shortcuts.actions.library_left", ["ArrowLeft"], "library"],
  ["library_right", "shortcuts.actions.library_right", ["ArrowRight"], "library"],
  ["library_up", "shortcuts.actions.library_up", ["ArrowUp"], "library"],
  ["library_down", "shortcuts.actions.library_down", ["ArrowDown"], "library"],
  ["library_first", "shortcuts.actions.library_first", ["Home"], "library"],
  ["library_last", "shortcuts.actions.library_last", ["End"], "library"],
  ["extend_prev", "shortcuts.actions.extend_prev", ["shift", "ArrowLeft"], "library"],
  ["extend_next", "shortcuts.actions.extend_next", ["shift", "ArrowRight"], "library"],
  ["deselect_all", "shortcuts.actions.deselect_all", [], "library"],
  ["select_active", "shortcuts.actions.select_active", [], "library"],
  ["toggle_side_panels", "shortcuts.actions.toggle_side_panels", [], "view"],
  ["toggle_all_panels", "shortcuts.actions.toggle_all_panels", [], "view"],
  ["white_balance", "shortcuts.actions.white_balance", [], "editing"],
  ["auto_adjust", "shortcuts.actions.auto_adjust", [], "editing"],
  ["auto_lens", "shortcuts.actions.auto_lens", [], "editing"],
  ["reset_adjustments", "shortcuts.actions.reset_adjustments", [], "editing"],
  ["brush_feather_up", "shortcuts.actions.brush_feather_up", [], "editing"],
  ["brush_feather_down", "shortcuts.actions.brush_feather_down", [], "editing"],
  ["mask_delete", "shortcuts.actions.mask_delete", ["Delete"], "editing"],
  ["open_folder", "shortcuts.actions.open_folder", [], "library"],
  ["import_photos", "shortcuts.actions.import_photos", [], "library"],
  ["rename_photos", "shortcuts.actions.rename_photos", [], "library"],
  ["refresh_library", "shortcuts.actions.refresh_library", [], "library"],
  ["open_people", "shortcuts.actions.open_people", [], "library"],
  ["toggle_tethering", "shortcuts.actions.toggle_tethering", [], "panels"],
  ["create_folder", "shortcuts.actions.create_folder", [], "library"],
  ["create_album", "shortcuts.actions.create_album", [], "library"],
  ["open_denoise", "shortcuts.actions.open_denoise", [], "editing"],
  ["open_negative", "shortcuts.actions.open_negative", [], "editing"],
  ["open_collage", "shortcuts.actions.open_collage", [], "editing"],
  ["open_panorama", "shortcuts.actions.open_panorama", [], "library"],
  ["open_hdr", "shortcuts.actions.open_hdr", [], "library"],
  ["open_focus_stack", "shortcuts.actions.open_focus_stack", [], "library"],
  ["shortcut_help", "shortcuts.actions.shortcut_help", [], "view"],
  ["rating_up", "shortcuts.actions.rating_up", [], "rating"],
  ["rating_down", "shortcuts.actions.rating_down", [], "rating"],
  ["go_back", "shortcuts.actions.go_back", ["Escape"], "view"],
  ["rate_advance_0", "shortcuts.actions.rate_advance_0", [], "rating"],
  ["rate_advance_1", "shortcuts.actions.rate_advance_1", [], "rating"],
  ["rate_advance_2", "shortcuts.actions.rate_advance_2", [], "rating"],
  ["rate_advance_3", "shortcuts.actions.rate_advance_3", [], "rating"],
  ["rate_advance_4", "shortcuts.actions.rate_advance_4", [], "rating"],
  ["rate_advance_5", "shortcuts.actions.rate_advance_5", [], "rating"],
  ["preset_create", "shortcuts.actions.preset_create", [], "editing"],
  ["preset_folder", "shortcuts.actions.preset_folder", [], "editing"],
  ["preset_import", "shortcuts.actions.preset_import", [], "editing"],
  ["preset_export", "shortcuts.actions.preset_export", [], "editing"],
  ["preset_sort", "shortcuts.actions.preset_sort", [], "editing"],
  ["mask_brush", "shortcuts.actions.mask_brush", [], "editing"],
  ["mask_linear", "shortcuts.actions.mask_linear", [], "editing"],
  ["mask_radial", "shortcuts.actions.mask_radial", [], "editing"],
  ["mask_subject", "shortcuts.actions.mask_subject", [], "editing"],
  ["mask_sky", "shortcuts.actions.mask_sky", [], "editing"],
  ["mask_luminance", "shortcuts.actions.mask_luminance", [], "editing"],
  ["mask_color", "shortcuts.actions.mask_color", [], "editing"],
  ["tether_capture", "shortcuts.actions.tether_capture", [], "editing"],
  ["tether_autofocus", "shortcuts.actions.tether_autofocus", [], "editing"],
  ["tether_detect", "shortcuts.actions.tether_detect", [], "editing"],
  ["tether_liveview", "shortcuts.actions.tether_liveview", [], "editing"],
  ["tether_ghost", "shortcuts.actions.tether_ghost", [], "editing"],
  ["finish_external_edit", "shortcuts.actions.finish_external_edit", [], "editing"],
  ["library_list", "shortcuts.actions.library_list", [], "library"],
  ["open_culling", "shortcuts.actions.open_culling", [], "library"],
  ["create_virtual_copy", "shortcuts.actions.create_virtual_copy", [], "library"],
  ["reveal_photo", "shortcuts.actions.reveal_photo", [], "library"],
] as const;
export type CommandId = (typeof entries)[number][0];
export type CommandSection = (typeof entries)[number][3];
export interface KeybindDefinition {
  action: CommandId;
  description: string;
  defaultCombo: string[];
  section: CommandSection;
}
export const KEYBIND_DEFINITIONS: KeybindDefinition[] = entries.map(([action, description, combo, section]) => ({
  action,
  description,
  defaultCombo: [...combo],
  section,
}));
export interface KeybindSection {
  id: CommandSection;
  label: string;
}
export const KEYBIND_SECTIONS: KeybindSection[] = ['library', 'editing', 'crop', 'view', 'rating', 'panels'].map(
  (id) => ({
    id: id as CommandSection,
    label: id === 'crop' ? 'shortcuts.crop' : `settings.keybinds.sections.${id}`,
  }),
);
